# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__   # checks version of numpy (.__version__)

'1.24.3'

In [3]:
import sys
sys.version

'3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

# below code we coverting list to array


In [6]:
#!pip install numpy

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
type(my_list)

list

In [13]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20,10)  # 1st arg < 2nd arg

array([], dtype=int32)

In [18]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.arange()

TypeError: arange() requires stop to be specified.

In [21]:
np.arange(10,30,5)  # 10 -starting, 30 -ending and 5 -step count

array([10, 15, 20, 25])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [23]:
np.arange(1,10,2,5)

TypeError: Cannot interpret '5' as a data type

In [24]:
np.zeros(3)  # parameter tunning

array([0., 0., 0.])

In [25]:
np.zeros(5, dtype=int)   # hyperparameter tunning

array([0, 0, 0, 0, 0])

- parameter  tunning - system bydefault give the parameter  
- Hyperparameter tunning - user wanted to change system parameter

In [26]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [27]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros((5,7))  # by default 1st arg -rows & 2nd arg -columns

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
np.ones(3)

array([1., 1., 1.])

In [32]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [34]:
np.ones((3,7),dtype=int)  # by default 3 -rows & 7 -columns

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [36]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [37]:
np.random.rand(5)

array([0.66514038, 0.28737447, 0.30131923, 0.44544758, 0.80762482])

In [38]:
np.random.rand(3,5)

array([[0.9175796 , 0.98910429, 0.1762169 , 0.44620218, 0.21324584],
       [0.2499571 , 0.80750039, 0.07114718, 0.85145326, 0.14649181],
       [0.44046424, 0.59070099, 0.41396083, 0.00453157, 0.32414518]])

In [46]:
np.random.randint(1,11,5)

array([4, 6, 4, 4, 2])

In [48]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [55]:
np.random.randint(1,12,(5,4))  # generate 5 rows and 4 columns between 1 to 11 excluding 12.

array([[ 1,  8,  4,  6],
       [10, 11,  7,  2],
       [11,  6,  2,  6],
       [ 7,  9,  8,  1],
       [ 8,  7, 10,  1]])

## Slicing in Matrix

In [56]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 12, 17, 16],
       [13, 12, 19, 10],
       [19, 18, 17, 16],
       [11, 16, 11, 12],
       [17, 12, 11, 17]])

In [57]:
type(b)

numpy.ndarray

In [58]:
b

array([[12, 12, 17, 16],
       [13, 12, 19, 10],
       [19, 18, 17, 16],
       [11, 16, 11, 12],
       [17, 12, 11, 17]])

In [59]:
b[:]

array([[12, 12, 17, 16],
       [13, 12, 19, 10],
       [19, 18, 17, 16],
       [11, 16, 11, 12],
       [17, 12, 11, 17]])

In [60]:
b[1:3]

array([[13, 12, 19, 10],
       [19, 18, 17, 16]])

In [61]:
b[1,2]

19

In [62]:
b[1,3]

10

In [63]:
b[1,-1]

10

In [64]:
b[-1,3]

17

In [65]:
b[-2,-3]

16

In [66]:
b[0:-2]

array([[12, 12, 17, 16],
       [13, 12, 19, 10],
       [19, 18, 17, 16]])

In [67]:
b[-4:2]

array([[13, 12, 19, 10]])

## Operations

In [68]:
a = np.random.randint(10,20,10)
a

array([15, 15, 13, 16, 10, 13, 11, 17, 18, 15])

In [69]:
id(a)

1594442108048

In [70]:
arr


array([0, 1, 2, 3, 4, 5])

In [71]:
arr2 = np.random.randint(0,100,(10,10))

In [72]:
arr2

array([[ 0, 68,  5, 82, 44,  9, 84, 54, 23, 35],
       [31, 33, 85, 13,  7, 89, 42, 88, 66, 56],
       [37, 73,  0, 26, 65, 28, 19,  5, 18, 31],
       [62, 76, 46, 87, 64, 70, 80, 80, 37, 19],
       [23, 68, 54, 23, 39, 38, 75, 27, 65, 82],
       [88, 25, 80, 10, 72,  9, 99, 88, 49, 86],
       [97, 58, 50, 73, 66, 54, 99,  1, 48, 50],
       [25, 47, 80,  8, 74, 57, 46,  8,  4,  6],
       [12, 72,  8, 13, 45, 66, 72, 60, 61, 99],
       [16, 93, 39, 60, 38, 89, 86, 62, 91, 73]])

In [73]:
arr2[::-1]

array([[16, 93, 39, 60, 38, 89, 86, 62, 91, 73],
       [12, 72,  8, 13, 45, 66, 72, 60, 61, 99],
       [25, 47, 80,  8, 74, 57, 46,  8,  4,  6],
       [97, 58, 50, 73, 66, 54, 99,  1, 48, 50],
       [88, 25, 80, 10, 72,  9, 99, 88, 49, 86],
       [23, 68, 54, 23, 39, 38, 75, 27, 65, 82],
       [62, 76, 46, 87, 64, 70, 80, 80, 37, 19],
       [37, 73,  0, 26, 65, 28, 19,  5, 18, 31],
       [31, 33, 85, 13,  7, 89, 42, 88, 66, 56],
       [ 0, 68,  5, 82, 44,  9, 84, 54, 23, 35]])

In [74]:
arr2[::-2]

array([[16, 93, 39, 60, 38, 89, 86, 62, 91, 73],
       [25, 47, 80,  8, 74, 57, 46,  8,  4,  6],
       [88, 25, 80, 10, 72,  9, 99, 88, 49, 86],
       [62, 76, 46, 87, 64, 70, 80, 80, 37, 19],
       [31, 33, 85, 13,  7, 89, 42, 88, 66, 56]])

In [75]:
arr2

array([[ 0, 68,  5, 82, 44,  9, 84, 54, 23, 35],
       [31, 33, 85, 13,  7, 89, 42, 88, 66, 56],
       [37, 73,  0, 26, 65, 28, 19,  5, 18, 31],
       [62, 76, 46, 87, 64, 70, 80, 80, 37, 19],
       [23, 68, 54, 23, 39, 38, 75, 27, 65, 82],
       [88, 25, 80, 10, 72,  9, 99, 88, 49, 86],
       [97, 58, 50, 73, 66, 54, 99,  1, 48, 50],
       [25, 47, 80,  8, 74, 57, 46,  8,  4,  6],
       [12, 72,  8, 13, 45, 66, 72, 60, 61, 99],
       [16, 93, 39, 60, 38, 89, 86, 62, 91, 73]])

In [77]:
arr2[::-2]

array([[16, 93, 39, 60, 38, 89, 86, 62, 91, 73],
       [25, 47, 80,  8, 74, 57, 46,  8,  4,  6],
       [88, 25, 80, 10, 72,  9, 99, 88, 49, 86],
       [62, 76, 46, 87, 64, 70, 80, 80, 37, 19],
       [31, 33, 85, 13,  7, 89, 42, 88, 66, 56]])

In [78]:
arr2[::2]

array([[ 0, 68,  5, 82, 44,  9, 84, 54, 23, 35],
       [37, 73,  0, 26, 65, 28, 19,  5, 18, 31],
       [23, 68, 54, 23, 39, 38, 75, 27, 65, 82],
       [97, 58, 50, 73, 66, 54, 99,  1, 48, 50],
       [12, 72,  8, 13, 45, 66, 72, 60, 61, 99]])

In [80]:
arr2

array([[ 0, 68,  5, 82, 44,  9, 84, 54, 23, 35],
       [31, 33, 85, 13,  7, 89, 42, 88, 66, 56],
       [37, 73,  0, 26, 65, 28, 19,  5, 18, 31],
       [62, 76, 46, 87, 64, 70, 80, 80, 37, 19],
       [23, 68, 54, 23, 39, 38, 75, 27, 65, 82],
       [88, 25, 80, 10, 72,  9, 99, 88, 49, 86],
       [97, 58, 50, 73, 66, 54, 99,  1, 48, 50],
       [25, 47, 80,  8, 74, 57, 46,  8,  4,  6],
       [12, 72,  8, 13, 45, 66, 72, 60, 61, 99],
       [16, 93, 39, 60, 38, 89, 86, 62, 91, 73]])

In [81]:
arr2[3:]

array([[62, 76, 46, 87, 64, 70, 80, 80, 37, 19],
       [23, 68, 54, 23, 39, 38, 75, 27, 65, 82],
       [88, 25, 80, 10, 72,  9, 99, 88, 49, 86],
       [97, 58, 50, 73, 66, 54, 99,  1, 48, 50],
       [25, 47, 80,  8, 74, 57, 46,  8,  4,  6],
       [12, 72,  8, 13, 45, 66, 72, 60, 61, 99],
       [16, 93, 39, 60, 38, 89, 86, 62, 91, 73]])

In [82]:
arr

array([0, 1, 2, 3, 4, 5])

In [83]:
arr.max()

5

In [84]:
arr.min()

0

In [85]:
arr.mean()

2.5

In [1]:
arr.median()

NameError: name 'arr' is not defined

In [6]:
from numpy import *
a = array([1,2,3,4,5])
median(a)

3.0

In [12]:
import numpy as np
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
mat[4,5]  # here 4 is row & 5 is column

45

In [16]:
mat[6]    # bydefault it represents rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
# with slices
mat[:, col]

In [17]:
mat[:,6]  # it will print columns

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [18]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
mat[0:10:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [21]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [23]:
mat[2:6,3:5]  # 2:6 will represent rows and 3:5 part will represent columns

array([[23, 24],
       [33, 34],
       [43, 44],
       [53, 54]])

In [24]:
mat[1:2,2:4]

array([[12, 13]])

## Masking or Numpy Filters

In [31]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [32]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
S